### PR TITLE
Vlv2TbltDevicePkg: port of code from CorebootPayloadPkg adding custom…

### PR DESCRIPTION
**Pull request by pietrushnic**
… Shell build

Signed-off-by: Piotr Król <piotr.krol@3mdeb.com>

### CODE REVIEW

**Comment by krystian-hebel** [comment]
Boots to menu, but trying to start boot manager results in

```
ASSERT_EFI_ERROR (Status = Not Found)
ASSERT [BdsDxe] /home/edk2/edk2/IntelFrameworkModulePkg/Universal/BdsDxe/BootMaint/BBSsupport.c(251): !EFI_ERROR (Status)
```

**Comment by pietrushnic** [comment]
@krystian-hebel let's rebase that code to make it work. In general the problem with with commit that `#if 0` BootOrder variable.

**Comment by miczyg1** [comment]
@krystian-hebel @pietrushnic is this PR reeady to merge or mergable? Do You plan to do anything regarding this change?

**Comment by krystian-hebel** [comment]
@miczyg1 after applying custom shell (trampoline) this will work even with `#if 0`, and would be compatible with swapping shell on Intel's image, before this concept was abandoned.

**Comment by pietrushnic** [comment]
@krystian-hebel you answer is not clear to me and I'm not sure about @miczyg1. @krystian-hebel please answer yes/no and then justify.

**Comment by krystian-hebel** [comment]
It can be merged, but built image wouldn't be bootable yet, as GUID of ShellPkg is different that this of ShellPkgBin added as a binary. After merging ul_4 this will become useful again.

**Comment by pietrushnic** [comment]
@miczyg1 @krystian-hebel I think this limitation is fair since `ul_4` have to be merged before release.

**Comment by pietrushnic** [comment]
@miczyg1 please merge.

**Pull request merged**
