### PR TITLE
Vlv2TbltDevicePkg/PlatformPkgGcc.fdf: integrate firmware binary

### PR DESCRIPTION
**Pull request by krystian-hebel**
RTNicPgX32.efi is empty for legal reasons.

Signed-off-by: Krystian Hebel <krystian.hebel@3mdeb.com>

### CODE REVIEW

**Comment by krystian-hebel** [comment]
@pietrushnic branch for UL2.3. Marked WIP until I fix problem with nonworking boot with custom shell.

**Comment by miczyg1** [comment]
Can we treat https://github.com/3mdeb/edk2-platforms/pull/6 as integrating binaries too? This change works too and is kind of duplicated (this change does not precise the location of binary)

**Comment by miczyg1** [comment]
@krystian-hebel delete please the commited binary and upload the binary to cloud. So that the init.sh will download it before building.

**Comment by pietrushnic** [comment]
@krystian-hebel we have to do that in different way, because in a way that you did that binary will persist in git objects.

Please:
1. do interactive rebase and edit first patch from this series as well as remove second patch
2. remove binary
3. amend commit and continue 
4. force push to branch from this PR

**Comment by krystian-hebel** [comment]
@pietrushnic done

**Review by pietrushnic — APPROVED** [review]

**Pull request merged**
